### ISSUE TITLE
Prepare Jakarta Bean Validation for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/beanvalidation-api#150]
Instructions
- [x]  Update text files
- [x]   Generate "boilerplate" specification project
- [x]   Make a staging release of the API from the master branch
- [x]   Make a release from the spec from the master branch
- [x]   Make a staging release of the TCK **from the 2.0 branch** and push it on downloads.eclipse.org
- [x]   Generate Stand-alone TCK test results
- [x]   Create a PR to jakartaee/specifications repository
- [x]   Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project

Details are [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_for_the_Jakarta_EE_8_Release):

**Comment by gunnarmorling** [comment]
@starksm64, it seems I cannot alter this issue (checking boxes in your description). Any idea how I can do that?
