### ISSUE TITLE
Automatic-Module-Name conflicts with jakarta.annotation-api

### ISSUE THREAD

**Issue by remal** [eclipse-ee4j/beanvalidation-api#159]
Both `jakarta.validation-api` and `jakarta.annotation-api` have the same Automatic-Module-Name - `java.validation`. It leads to compilation errors. Please fix it.

* https://github.com/eclipse-ee4j/beanvalidation-api/blob/9e42361f5de19c4176abbd44faff85b7aa020c46/pom.xml#L137
* https://github.com/eclipse-ee4j/common-annotations-api/blob/eee711ae7e13fc318dd197d631389764f964df8d/api/pom.xml#L258

**Comment by gsmet** [comment]
I don't understand this report? One is `java.validation`, the other is `java.validation`.

**Comment by remal** [comment]
Opened by mistake. Closing.
