### ISSUE TITLE
Added uses statements to module-info.java

### ISSUE THREAD

**Issue by dkkopp** [eclipse-ee4j/beanvalidation-api#172]
Currently, the beans validation API is failing at runtime for me when I attempt to use it with the Java Module System. The runtime complains that the beans validation module-info does not contain a "uses" clause.

To fix this, please add the following to module-info.java:

    uses jakarta.validation.spi.BootstrapState;
    uses jakarta.validation.spi.ConfigurationState;
    uses jakarta.validation.spi.ValidationProvider;

I have tried this on my machine, and it works.

Thank you.

**Comment by starksm64** [comment]
Resolved via #173
