### ISSUE TITLE
Jakarta.validation API 3.0.1 is backward incompatible

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/beanvalidation-api#175]
The API contains OSGi header `Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=9.0))"`, unlike the 3.0.0 API.

This requirement for JDK 9 is a backward-incompatible change that should not be introduced in a service release of the API.

**Comment by senivam** [comment]
according to https://jakarta.ee/specifications/bean-validation/3.0/ it shall support JDK 1.8

**Comment by gsmet** [comment]
Hey there,

Can you make sure this PR https://github.com/eclipse-ee4j/beanvalidation-api/pull/177 fixes the issue for you?

**Comment by senivam** [comment]
looks good to me, thank you.
