### ISSUE TITLE
Publish the version 3.0.2

### ISSUE THREAD

**Issue by Thihup** [eclipse-ee4j/beanvalidation-api#176]
I'm trying to use the Bean Validation with the module system, and it requires the `uses`. It was already fixed, but I'd like to know when this fix will be published.
Currently, it is blocking me to use the module system correctly, so it would be great if the fix is published soonish.

**Comment by starksm64** [comment]
Yes, pending the #177 fix for #175 a new release will be put out today or as soon as that PR is merged.

**Comment by gsmet** [comment]
@starksm64 we are good to go!

**Comment by starksm64** [comment]
The release has been built and pushed out to maven central. It should be visible from there within 24 hours.

**Comment by senivam** [comment]
@starksm64 thanks a lot
